---
# Adapted from Linuxcnc's ci.yml action
#
# LinuxCNC-Ethercat depends on both LinuxCNC and Ethercat Master; both
# need to be compiled from source.  This creates a job for each and
# attempts to cache the results.  Worst-case, this will result in a ~5
# minute run while dependencies are installed and code builds.  Best
# case, it will take a few seconds each to verify and restore caches,
# and then we can get started building code that we care about.
#
# As of 2023-12-17, builds with a hot cache take about 40 seconds.

name: Build CI

on:  # yamllint disable-line rule:truthy
    push:
        branches: [master]
    pull_request:
    release:
        types: [published]
    check_suite:
        types: [rerequested]

permissions:
    contents: read  # to fetch code (actions/checkout)

jobs:
    # Build LinuxCNC itself.  The result is cached, probably too aggressively.
    build-linuxcnc:
        runs-on: ubuntu-20.04
        steps:
            - name: cache linuxcnc
              id: cache-linuxcnc
              uses: actions/cache@v3
              env:
                  cache-name: cache-linuxcnc
              with:
                  key: ${{ runner.os }}-build-${{ env.cache-name }}
                  path: linuxcnc/

            - name: Checkout linuxcnc
              if: ${{ steps.cache-linuxcnc.outputs.cache-hit != 'true' }}
              uses: actions/checkout@v4
              with:
                  repository: linuxcnc/linuxcnc
                  path: linuxcnc/
                  submodules: true
                  fetch-depth: 0

            - name: install linuxcnc deps
              if: ${{ steps.cache-linuxcnc.outputs.cache-hit != 'true' }}
              run: |
                  set -x
                  cd linuxcnc
                  # LinuxCNC provides a script to install deps, but it installs *way* too many things,
                  # including TeX and most of X
                  ./scripts/travis-install-build-deps.sh

                  #curl -O https://snapshot.debian.org/archive/debian/20220716T154603Z/pool/main/p/po4a/po4a_0.67-2_all.deb
                  #sudo apt install --yes ./po4a_0.67-2_all.deb
                  #sudo apt --quiet --yes upgrade

            - name: Build linuxcnc
              if: ${{ steps.cache-linuxcnc.outputs.cache-hit != 'true' }}
              run: |
                  set -x
                  cd linuxcnc
                  cd src
                  ./autogen.sh
                  ./configure \
                  --with-realtime=uspace \
                  --disable-check-runtime-deps \
                  --disable-gtk \
                  --enable-non-distributable=yes
                  make -O -j$((1+$(nproc))) default pycheck V=1

    # Build Ethercat Master, caching the result.
    build-ethercatmaster:
        runs-on: ubuntu-20.04
        steps:
            - name: cache Ethercat Master
              id: cache-ethercatmaster
              uses: actions/cache@v3
              env:
                  cache-name: cache-ethercatmaster
              with:
                  key: ${{ runner.os }}-build-${{ env.cache-name }}
                  path: ethercat/

            - name: Fetch EtherCAT Master
              if: ${{ steps.cache-ethercatmaster.outputs.cache-hit != 'true' }}
              run: |
                  set -x
                  git clone https://gitlab.com/etherlab.org/ethercat.git

            - name: Build EtherCAT Master
              if: ${{ steps.cache-ethercatmaster.outputs.cache-hit != 'true' }}
              run: |
                  set -x
                  cd ethercat
                  ./bootstrap
                  ./configure --disable-kernel
                  make -j$((1+$(nproc))) all
                  #sudo make install

    # Build LinuxCNC-Ethercat itself.
    build:
        needs:
            - build-linuxcnc
            - build-ethercatmaster
        runs-on: ubuntu-20.04
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

            - name: Checkout linuxcnc-ethercat
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sh -x
                  sudo apt install yapps2

            - name: Restore LinuxCNC cache
              uses: actions/cache/restore@v3
              env:
                  cache-name: cache-linuxcnc
              with:
                  key: ${{ runner.os }}-build-${{ env.cache-name }}
                  path: linuxcnc/

            - name: Restore Ethercat Master cache
              uses: actions/cache/restore@v3
              env:
                  cache-name: cache-ethercatmaster
              with:
                  key: ${{ runner.os }}-build-${{ env.cache-name }}
                  path: ethercat/

            - name: Install linuxcnc locally
              run: |
                  set -x
                  cd linuxcnc/src
                  sudo make install-kernel-indep
                  echo "$GITHUB_WORKSPACE/linuxcnc/bin" >> $GITHUB_PATH

            - name: Install EtherCAT Master locally
              run: |
                  set -x
                  cd ethercat
                  sudo make install

            - name: make
              run: |
                  make COMP=$GITHUB_WORKSPACE/linuxcnc/bin/halcompile -j$((1+$(nproc)))

    # Build LinuxCNC-Ethercat debian package
    prep-debian-package:
        env:
            CHANGELOG_AUTHOR_NAME: "Scott Laird"
            CHANGELOG_AUTHOR_EMAIL: "scott@sigkill.org"
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Patch changelog (snapshot)
              uses: pi-top/git-debian-changelog-bump-action@master
              with:
                  release: false
                  author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
                  author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}

            - name: Determine current version
              run: |
                  sudo apt install -y dpkg-dev
                  echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV
